name: cs559-hw
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python==3.8
  - tensorflow-gpu=2.3
  - cudatoolkit
  - numpy
  - pandas
  - pillow
  - pip
  - pip:
      - zipfile38
